### PR TITLE
Fixing assignment of admin in BaseTest for the case in which it doesn…

### LINKED ISSUE #135: Tests failing with admin user not found
BaseTest is failing to initialize with a clean database, because the admin DAO throws an exception when an admin email isn't found, rather than returning null as the code expects.

### PR DESCRIPTION
**Pull request by jottinger**
…'t exist on the datastore

Fixes #135

### CODE REVIEW

File: src/test/kotlin/javabot/BaseTest.kt [hunk 1]
```diff
@@ -77,15 +77,16 @@ open class BaseTest {
...
-            admin.ircName = testUser.nick
-            admin.emailAddress = BOT_EMAIL
-            admin.hostName = testUser.hostmask
-            admin.botOwner = true
+        var admin = try {
+            adminDao.getAdminByEmailAddress(BOT_EMAIL)
+        } catch(adminNotFound: RuntimeException) {
+            Admin(testUser.nick, BOT_EMAIL, testUser.hostmask, true)
         }
+        admin.ircName = testUser.nick
```
Comment (evanchooly) [inline src/test/kotlin/javabot/BaseTest.kt]: These next assignment lines are redundant now.  Also, nice use of the try-as-an-expression feature of kotlin.  :)
