### PR TITLE
Correct "not on earth" city name

### LINKED ISSUE #272: Weather API broken
This is due to two things:

1. The token expired (external causes, and has been fixed for the actual bot's token)
1. The tests do a craptastic job of handling DST

### PR DESCRIPTION
**Pull request by jottinger**
Change initial TZ search to Phoenix so it's a consistent timezone
Add DST handling for the New York TZ search

Closes #272.

### CODE REVIEW

File: src/test/kotlin/javabot/operations/WeatherOperationTest.kt [hunk 1]
```diff
@@ -6,6 +6,10 @@ import org.testng.Assert.assertEquals
 import org.testng.annotations.Test
 import java.text.ParseException
 import java.text.SimpleDateFormat
+import java.time.ZoneId
+import java.time.ZonedDateTime
+import java.time.format.DateTimeFormatter
+import java.util.*
```
Comment (evanchooly) [inline src/test/kotlin/javabot/operations/WeatherOperationTest.kt]: i should add ktlint to the build.  i hate * imports
